### ISSUE TITLE
fix stylesheet types

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epic-stack#177]
`'fontStylestylesheetUrl' is deprecated.ts(6385) client.d.ts(42, 6): The declaration was marked as deprecated here.`

```diff
-  import fontStylestylesheetUrl from './styles/font.css'
-  import tailwindStylesheetUrl from './styles/tailwind.css'
+  import fontStylestylesheetUrl from './styles/font.css?inline'
+  import tailwindStylesheetUrl from './styles/tailwind.css?inline'
```

why we need this duplication in the same function?
https://github.com/epicweb-dev/epic-stack/blob/f21bbe93ce26b3ff391874a102e8a7c83319be11/app/root.tsx#L40-L43
https://github.com/epicweb-dev/epic-stack/blob/f21bbe93ce26b3ff391874a102e8a7c83319be11/app/root.tsx#L63-L65

**Comment by xHomu** [comment]
It's a bit verbose, but that line solves this particular warning in Lighthouse:

![image](https://github.com/epicweb-dev/epic-stack/assets/84349818/1747fb89-94b8-4264-911a-5e900f3ae82d)

Details on preloading CSS: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

This lets the main thread to continue rendering the HTML while the css streams in. Otherwise, html rendering is on hold until all CSS comes in.
