### ISSUE TITLE
Remove --sourcemap from 'remix build' script

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#178]
We should probably remove `--sourcemap` from the `remix build` command.

From GitHub Action:
<img width="1523" alt="Screenshot 2023-06-14 at 16 18 43" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/cb4a48e9-9090-4df1-a31e-b03de224215d">

**Comment by kentcdodds** [comment]
Nope, we need it for sentry monitoring and better debugging in production. That warning is annoying, but the way we have things set up we shouldn't leak anything secret because all secrets use environment variables and we don't hard code them. Maybe there should be a docs page on environment variables and adding secrets in general.

**Comment by scefali** [comment]
@kentcdodds I thought about changing the logic to make source maps only generate source maps when Sentry has the necessary environment variables to upload source mpas, but that adds additional layers of logic. If you think it's worth it though I can add it.

**Comment by kentcdodds** [comment]
Nah, it's also useful for production debugging. Thanks though.

**Comment by ryanwoodcox** [comment]
@kentcdodds 
Is there anyway to generate front-end only source maps? I get the desire to debug in production, but (assuming the warning is accurate) exposing server-side source code in the browser feels very wrong. We would be giving attackers so much information regarding our database schema, backend auth logic as well as handing over proprietary logic to competitors.

In the spirit of Epic Stack (providing a stable foundation based on experienced developers), I am struggling with this decision. Acknowledging I can simply remove the `--sourcemap` flag on my end, I am concerned for the other consumers of this stack that may not realize the implications here.

Anyone experienced in security willing to weigh in here?

**Comment by kentcdodds** [comment]
I'm afraid there is no way to generate front-end only source maps.

Security through obscurity is poor practice and while I appreciate that we want to limit the amount of tools adversaries have to compromise our systems, we also have observability to be concerned about.

I would be open to a contribution that prevents the sourcemaps being sent to the browser. A simple edit in the express file should make this possible. It could be cool to make it so the sourcemaps are only visible to an authenticated user. Definitely possible, but not something I have time to work on myself.

**Comment by wrporter** [comment]
I agree with

> Security through obscurity is poor practice

One case that is important to guard against is company Intellectual Property. Exposing an entire application's source code that may be in a private repository. I'm not a security expert, but as @ryanwoodcox mentions above, it might be worth adding a comment in `vite.config.ts` to explain the consequences of doing this and that it may not be suitable for everyone. 

I say this because this is the most well-developed React Router template (that I have seen) and many may use it without the experience to recognize these kinds of tradeoffs.
