### ISSUE TITLE
ChatGPT link in TOTP Decision Docs 404s

### ISSUE THREAD

**Issue by DigitalGoldfish** [epicweb-dev/epic-stack#248]
The link https://chat.openai.com/share/a1bbd00d-c9d7-4846-a9af-12c6a475cd20 in the [TOTP Decision](https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/014-totp.md) shows a 404 page. It happens to me both as an anonymous user and when I am logged in at openai.com.

**Comment by kentcdodds** [comment]
That's pretty sad :( I should have saved it elsewhere because this is all I see when I try to go to that conversation:

![image](https://github.com/epicweb-dev/epic-stack/assets/1500684/19b8b4f5-4448-4a74-aa23-7263107c7cd6)

Maybe it's just an issue with their infra not being able to serve that size of a conversation and one day we'll be able to see it again, but right now it doesn't look like it can handle it :(
