### ISSUE TITLE
Unable to update the profile pic when javascript is disabled

### ISSUE THREAD

**Issue by mohammedzamakhan** [epicweb-dev/epic-stack#311]

**Comment by kentcdodds** [comment]
Confirmed. Ideas and PR welcome :)

**Comment by evayde** [comment]
The issue here is that there is no submit button, and the change event is not triggered as it runs on the client.
The most straightforward solution would probably be to add a submit button in a noscript-tag. 

Or do you know a Remix way to handle this? @kentcdodds

**Comment by kentcdodds** [comment]
@evayde that sounds fine. To whoever opens the PR, I'd appreciate a video demonstrating that it works. :)

**Comment by evayde** [comment]
I quickly checked it out and glimpsed over it. Unfortunately, there are some more things to consider, probably also good to keep them in mind for future challenges:

**1. UX Considerations**

This is bad:

https://github.com/epicweb-dev/epic-stack/assets/25255815/1414de63-2298-4295-b5f1-26a9f9e615de

(I have to click on edit, choose a picture, then click save). The buttons don't indicate that I have to take these steps. I know this is not really a real-world issue, as probably no user ever sees this, but still an interesting problem.

I have a possible solution for this: Since this input field is required, we can create a CSS class (but this is not possible with TW inline classes, I assume). We can use the input:valid pseudo-class to hide the submit button and only show it when the element is filled. This way we can mimic the JS behavior.
I have quickly implemented a proof of work and this is what it would look like using the CSS solution. Note that JS is disabled here.

https://github.com/epicweb-dev/epic-stack/assets/25255815/152c0248-1db2-4e2c-bda0-4ba8bc79b5cb

**2. It's possible to break the form**

The form breaks when hitting save first. Afterwards, it's not possible anymore to open the upload dialog. The user has to refresh the page:

https://github.com/epicweb-dev/epic-stack/assets/25255815/c9ef2f7f-0631-4471-a67f-da6d185cec75

This has to be further debugged; I didn't see why it's not working at first glance. But maybe it's also not a problem if we hide the save button before the input element is filled. I'd still rather have a look into it.

I think these issues should be addressed before moving forward, as an immature solution only causes us to revisit this issue at a later time.

**Comment by kentcdodds** [comment]
Thanks for looking into this.

To be clear, "works without JavaScript" is not a high priority for this stack. I'm willing to add minimal code changes to make it function, but the primary benefit of "works without JavaScript" is the mental model you get for data loading and mutations. The profile image chooser loses that a little bit in favor of a smoother UX (which is why it's a little more complicated), but sometimes trying to get a smooth UX and "works without JS" can lead to some pretty weird code.

Like I said, I'm definitely willing to entertain a PR for improving this experience, I just wanted to make sure it was clearly understood that if we have to choose between something really complicated and accepting that it won't work without JS, then I will choose the later.

Oh, and on this:

> but this is not possible with TW inline classes, I assume

It actually is! https://tailwindcss.com/docs/hover-focus-and-other-states#invalid

**Comment by evayde** [comment]
> but this is not possible with TW inline classes, I assume

It would require a selector such as `input:valid ~ button[type='submit']`, I haven't seen this in Tailwind, yet.

> if we have to choose between something really complicated and accepting that it won't work without JS, then I will choose the later.

That was also my impression, which is why I rather wanted to check back with possible solutions than implement something that's unwanted. Although, it might be really interesting for some users, having a solution at this small scale could be worth it. 
I will add a PR for this later, then we can decide this with an actual implementation.

Btw., is this something for a decision document? Like "When do we stop supporting disabled JS"?

**Comment by kentcdodds** [comment]
Using regular CSS is totally fine if it's too challenging to make it work with Tailwind 👍

I'm not certain whether this is worth a decision document. Possibly!
