### ISSUE TITLE
Add CSRF protection to forms

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/epic-stack#370]
using remix-utils

**Comment by sergiodxa** [comment]
Don’t use Remix Utils CSRF, or use it as a base to implement your own, in Remix Utils I used the session, I later found out that setting the session on the root loader can cause a race condition if another loader does the same (which happens when using OAuth2), so it’s better to keep the CSRF token in a separate cookie that no other route will set. You can still use Remix Utils components though.

**Comment by sergiodxa** [comment]
yes, on the next major release I'm planning after v2 of Remix

**Comment by sergiodxa** [comment]
This is the new implementation for cookie-based CSRF protection on Remix Utils https://github.com/sergiodxa/remix-utils/tree/remix-v2#csrf.

The [PR](https://github.com/sergiodxa/remix-utils/pull/215) with the change will not be merged until Remix v2 ships to sync the major releases, I'm working on other breaking changes too. Mostly to update things to use latest features.

**Comment by swalker326** [comment]
This is rdy to go now? I can try to tackle this if no one else is working on it.

**Comment by kentcdodds** [comment]
I implemented this a week or two ago and forgot to close the issue 😅
