### ISSUE TITLE
Source code and tests inside deployed container

### ISSUE THREAD

**Issue by kandros** [epicweb-dev/epic-stack#375]
Is this intended?
![CleanShot 2023-08-05 at 14 07 59@2x](https://github.com/epicweb-dev/epic-stack/assets/4562878/04c81e63-172d-44da-aedc-f550fa54210c)
![CleanShot 2023-08-05 at 14 09 43@2x](https://github.com/epicweb-dev/epic-stack/assets/4562878/890a92de-f672-4e63-80d6-7b00c309d91e)

**Comment by kentcdodds** [comment]
Yes, we add everything to the docker image toward the end of the Dockerfile because it's easier than adding only the necessary bits. It's just easy to miss something or forget to add something if you change it in the future. I would definitely entertain a pull request for being more explicit. I'm just worried someone will add a config needed at runtime and they won't realize they need to add it in the Dockerfile as well so they'll spend hours wondering why the deployed version doesn't work.
