### ISSUE TITLE
OTP-Links in Email

### ISSUE THREAD

**Issue by DigitalGoldfish** [epicweb-dev/epic-stack#410]
OTP-Links in Emails (e.g. the signup confirmation code) sent to Outlook Mailboxes with Safe Links enabled (default Settings) don't work when the user clicks the link. The OTP Code also doesn't work when entered manually.

The reason for this is that MS Outlook/MS Defender queries these links during the security check and as a result the entry in the verification table is removed. This only happens with a public domain name, it is not reproducable when testing on localhost. 

Documentation about Safe Links from MS: https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide.

**Comment by kiliman** [comment]
Wow, that seems like a dumb feature. Spammers must love it because they now have a live hit and know the email address is valid. That's one of the reasons email clients stopped displaying images from unknown senders. So they wouldn't log the image request.

Definitely not something you would expect to happen. We have Office 365 so I'll make sure that is disabled.

**Comment by kentcdodds** [comment]
I'm sure there's some documented way to determine whether the request is coming via "Safe Links" and skip deleting the validation code if that's the case. Could you look into this @DigitalGoldfish?

**Comment by kiliman** [comment]
Based on this thread https://github.com/FusionAuth/fusionauth-issues/issues/629 it sounds like Outlook Safe Links sends a `HEAD` request to the URL. Since Remix will call the loader for both `HEAD` **and** `GET` requests, this is what is causing the validation to trigger.

Looks like you should only process this for `GET` requests. For `HEAD` just return `new Response('OK', { status: 200 })`

**Comment by kentcdodds** [comment]
That note is a good one. Normally, side effects on GETs are not desirable anyway. Another option could be to require the user to submit the form. But I think in this case we can just check the method.

**Comment by DigitalGoldfish** [comment]
@kiliman Thanks for the link, that was helpful. I can confirm that there is a HEAD request but this code block in the loader  doesn't prevent the safe link from invalidating the code. I know it triggers cause I can see the log message but so it shouldn't call validateRequest but there is something I am missing.

```
if (request.method === 'HEAD') {
	console.log('Blocked HEAD request');
	throw new Response('OK', { status: 200 });
}
```

**Comment by DigitalGoldfish** [comment]
The HEAD request is triggered when the user clicks on the link in the mail.

But before the email is even delivered to the mailbox there is a GET requests to the URL. I assume this is MS Defender scanning the email and trying to determine if it should quarantine it or not.  So far I don't see a way to identify this requests other than the user agent string showing an outdated (but changing) version of chrome.

**Comment by kentcdodds** [comment]
I think your solution is a good one. I'm just curious about what others do because I've definitely seen this approach elsewhere.

**Comment by DigitalGoldfish** [comment]
This [comment](https://github.com/FusionAuth/fusionauth-issues/issues/629#issuecomment-1509992837) explains how https://magiclinks.dev/ solved the problem. Short summary: using recaptcha.

And here is how opencollective solved it:https://github.com/opencollective/opencollective-frontend/pull/5476
Short Summary: by examining the user agent string

I didn't find any other solutions but maybe I am searching wrong. Most also only talk about the head request not about the gets. But I've also read somewhere that even a JS triggered form submit is triggered by the bot so it's not that easy to find a good clean workaround.

**Comment by kentcdodds** [comment]
Boy that's a big pain in the neck. Perhaps an alternative is to not delete the verification right away. It expires after a half hour anyway so maybe that's fine?

**Comment by DigitalGoldfish** [comment]
Sound like the best idea to me in regards to UX. Not sure about security implications.

**Comment by JohnMaguire** [comment]
I stumbled across this ticket as I'm currently fighting this issue as well, unrelated to this project.

Something to note about magiclinks.dev's solution is that they are using [reCAPTCHA v3](https://developers.google.com/recaptcha/docs/v3) which returns a score for users instead of presenting them with a challenge.

If this returns a poor user score, they show a "Verify" button that the user must click (again, not a challenge.) We are considering showing this button, either with or without validating the user via reCaptcha first.

One thing to note about allowing the authentication credential to continue living after the link is visited is that the authentication credential may also appear in third-party logging systems since they are requesting the endpoint URL, containing the credential. So since there is sort of "known exposure" of this credential, I was hoping to avoid its continuing to live.

**Comment by dawnmist** [comment]
We've had issues with this at work - it's very common for email programs to test links by scanning them, so having links in emails that trigger server-side functions on-click without further user interaction is hugely problematic.

One potential solution I've used for email logins is to create a link that has the email and code to be validated as a query string that is then used to populate a confirmation form on a page. That allows the user to click on the link in the email, or by also showing the code to be able to copy/paste the code into the form manually, and then submit the form to complete the login/validate the code. The email program can still "click" on the link in its tests, but doesn't activate the validation itself by doing so because the form returned to the email client isn't submitted in its link test.

**Comment by kentcdodds** [comment]
I removed the auto-submitted functionally in the loader. Thanks!
