### ISSUE TITLE
Refactoring `DataFunctionArgs` to `LoaderFunctionArgs` and `ActionFunctionArgs`

### ISSUE THREAD

**Issue by diegotc86** [epicweb-dev/epic-stack#573]
Hi Kent,

I've noticed that The Epic Stack is utilizing `DataFunctionArgs` for the loaders and actions arguments, while the Remix documentation now advises using `LoaderFunctionArgs` and `ActionFunctionArgs`. If you think updating this would be beneficial, I'd be happy to assist.

The action plan involves identifying all instances where `DataFunctionArgs` is used, replacing it with the appropriate type, and updating the imports as needed.

P.S.: I've already located these instances. My only uncertainty is regarding the file `entry.server.ts`, where `DataFunctionArgs` is employed to type the `handleError` function. I believe `LoaderFunctionArgs` would be a suitable replacement here.

**Comment by jacobparis** [comment]
This will need to be addressed before Client Data comes to the Epic Stack, and since it's in unstable pre-release now I think it'd be a good time

Regarding handleError, I think we can actually delete it? It doesn't appear to be used https://github.com/search?q=repo%3Aepicweb-dev%2Fepic-stack%20handleError&type=code

https://github.com/remix-run/remix/discussions/7634#discussioncomment-7256034

**Comment by kentcdodds** [comment]
I'm really bummed about this decision by Remix, but whatever it's fine.

`handleError` is used by remix: https://remix.run/docs/en/main/file-conventions/entry.server#handleerror

Anyone can feel free to make this change. PRs welcome.

**Comment by jacobparis** [comment]
> handleError is used by remix: https://remix.run/docs/en/main/file-conventions/entry.server#handleerror

Ah makes sense, then @diegotc86 as documented there you can use the type `LoaderFunctionArgs | ActionFunctionArgs` for that function
