### ISSUE TITLE
Throwing redirects doesn't work and it's caught by the ErrorBoundary

### ISSUE THREAD

**Issue by edygar** [epicweb-dev/epic-stack#632]
Here's a minimal reproducible example:

- Clone and setup https://github.com/edygar/epic-stack-bug
- Then access http://localhost:3000/users/kody/notes/d27a197e

The exception was caught by the errorboundary and it's displayed as an error instead of redirecting:
![image](https://github.com/epicweb-dev/epic-stack/assets/566280/8bb70f11-a72f-4fdb-9e5d-8c422895cb37)

**Comment by kiliman** [comment]
The issue is that you're trying to redirect from a "loader' and expecting the root loader to execute and display your toast message. Remix will only automatically revalidate on mutatations. You can force your root loader to run by using `redirectDocument` instead.

As for the error, did you check your dev console to see what the error was?

**Comment by edygar** [comment]
The error was the Response object (with the redirect)

**Comment by kentcdodds** [comment]
No, the real issue is this: https://github.com/remix-run/remix/discussions/7043

The solution is to add `await` in front of the utility.
