### ISSUE TITLE
Missing Hot Data reload??

### ISSUE THREAD

**Issue by natac13** [epicweb-dev/epic-stack#635]
https://github.com/epicweb-dev/epic-stack/blob/430947ac60ba630d16209db86e0e860deb215045/server/index.ts#L199

I think this line has to be a function call which returns `ssrLoadModule` call. I noticed that without it being a function there is no hot data reload in a loader. HMR worked on the JSX but not in the loader. 

I changed this to a function in my app and things began to work again. 

I just wanted to share this info and to see if you were experiencing the same "no hot data reload"

**Comment by kentcdodds** [comment]
Hmmm... I'm getting a refresh whenever I change my loader. Not HMR though. When I try to change that to a function I get an error because this is actually already in a function (the `getBuild` function) which is passed as-is to the `createRequestHandler` during development. So we are actually providing a function already.

Like I said, I'm getting a full-page refresh when I change my loader so that seems wrong too. I could be misunderstanding you though. Maybe it would help if you made a pull request?
