### ISSUE TITLE
Makes sense to substitute Express for Fastify?

### ISSUE THREAD

**Issue by rustworthy** [epicweb-dev/epic-stack#670]
Hi there!

This is an awesome stack and a lot of efforts and time invested for the community benefit.

I'd like to suggest something. How about switching onto [`fastify`](https://fastify.dev/), which is a new generation framework and
could fit the epic stack nature ideally. Here is short summary from `Nest.js` [documentation](https://docs.nestjs.com/techniques/performance) on the underlying framework, which is of interest I believe.

There's  a community maintained [remix-fastify adapter](https://github.com/mcansh/remix-fastify) and one missing piece - the wrapper over the wrapper :sweat_smile: in Sentry - I hope will be [covered](https://github.com/getsentry/sentry-javascript/pull/11261) soon. As for the middleware used in the epic stack's Express server app - a quick walk-through shows they are all available in `Fastify` ecosystem.

It goes without saying, there should be a proof of concept first, which I'd love to implement and tag accordingly :smile: 

What's your opinion on this change suggestion in general?

**Comment by fredericrous** [comment]
my humble opinion, epic stack should wait for fastify to become a remix official adapter. switching to a community driven adapter doesn't seem wise for a broad usage for the number 1 template for remix. But that shouldn't stop you from forking the template and creating a PR to add it to https://github.com/epicweb-dev/epic-stack/blob/main/docs/examples.md

**Comment by kentcdodds** [comment]
An example would definitely be welcome.

I'm not very interested in changing the built-in server until Remix finishes the work they're doing on solving "the middleware problem." Because when they do then we'll ditch the built-in server in favor of using Remix for everything anyway.

Express is good enough to get us to that point.

Here's an old discussion about this. Feel free to move further discussion here: https://github.com/epicweb-dev/epic-stack/discussions/511
